/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models.tables.records;


import com.optiply.infrastructure.data.models.tables.Webshop;
import com.optiply.infrastructure.data.models.tables.interfaces.IWebshop;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebshopRecord extends UpdatableRecordImpl<WebshopRecord> implements Record4<Long, String, String, Short>, IWebshop {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>webshop.webshopId</code>.
     */
    @Override
    public WebshopRecord setWebshopid(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>webshop.webshopId</code>.
     */
    @Override
    public Long getWebshopid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>webshop.handle</code>.
     */
    @Override
    public WebshopRecord setHandle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>webshop.handle</code>.
     */
    @Override
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>webshop.url</code>.
     */
    @Override
    public WebshopRecord setUrl(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>webshop.url</code>.
     */
    @Override
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>webshop.interestRate</code>.
     */
    @Override
    public WebshopRecord setInterestrate(Short value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>webshop.interestRate</code>.
     */
    @Override
    public Short getInterestrate() {
        return (Short) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Short> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, Short> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Webshop.WEBSHOP.WEBSHOPID;
    }

    @Override
    public Field<String> field2() {
        return Webshop.WEBSHOP.HANDLE;
    }

    @Override
    public Field<String> field3() {
        return Webshop.WEBSHOP.URL;
    }

    @Override
    public Field<Short> field4() {
        return Webshop.WEBSHOP.INTERESTRATE;
    }

    @Override
    public Long component1() {
        return getWebshopid();
    }

    @Override
    public String component2() {
        return getHandle();
    }

    @Override
    public String component3() {
        return getUrl();
    }

    @Override
    public Short component4() {
        return getInterestrate();
    }

    @Override
    public Long value1() {
        return getWebshopid();
    }

    @Override
    public String value2() {
        return getHandle();
    }

    @Override
    public String value3() {
        return getUrl();
    }

    @Override
    public Short value4() {
        return getInterestrate();
    }

    @Override
    public WebshopRecord value1(Long value) {
        setWebshopid(value);
        return this;
    }

    @Override
    public WebshopRecord value2(String value) {
        setHandle(value);
        return this;
    }

    @Override
    public WebshopRecord value3(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public WebshopRecord value4(Short value) {
        setInterestrate(value);
        return this;
    }

    @Override
    public WebshopRecord values(Long value1, String value2, String value3, Short value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IWebshop from) {
        setWebshopid(from.getWebshopid());
        setHandle(from.getHandle());
        setUrl(from.getUrl());
        setInterestrate(from.getInterestrate());
    }

    @Override
    public <E extends IWebshop> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WebshopRecord
     */
    public WebshopRecord() {
        super(Webshop.WEBSHOP);
    }

    /**
     * Create a detached, initialised WebshopRecord
     */
    public WebshopRecord(Long webshopid, String handle, String url, Short interestrate) {
        super(Webshop.WEBSHOP);

        setWebshopid(webshopid);
        setHandle(handle);
        setUrl(url);
        setInterestrate(interestrate);
    }

    /**
     * Create a detached, initialised WebshopRecord
     */
    public WebshopRecord(com.optiply.infrastructure.data.models.tables.pojos.Webshop value) {
        super(Webshop.WEBSHOP);

        if (value != null) {
            setWebshopid(value.getWebshopid());
            setHandle(value.getHandle());
            setUrl(value.getUrl());
            setInterestrate(value.getInterestrate());
        }
    }
}
