/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models.tables.daos;


import com.optiply.infrastructure.data.models.tables.Webshopservicelevels;
import com.optiply.infrastructure.data.models.tables.records.WebshopservicelevelsRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebshopservicelevelsDao extends DAOImpl<WebshopservicelevelsRecord, com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels, Long> {

    /**
     * Create a new WebshopservicelevelsDao without any configuration
     */
    public WebshopservicelevelsDao() {
        super(Webshopservicelevels.WEBSHOPSERVICELEVELS, com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels.class);
    }

    /**
     * Create a new WebshopservicelevelsDao with an attached configuration
     */
    public WebshopservicelevelsDao(Configuration configuration) {
        super(Webshopservicelevels.WEBSHOPSERVICELEVELS, com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels.class, configuration);
    }

    @Override
    public Long getId(com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels object) {
        return object.getWebshopid();
    }

    /**
     * Fetch records that have <code>webshopId BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels> fetchRangeOfWebshopid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Webshopservicelevels.WEBSHOPSERVICELEVELS.WEBSHOPID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>webshopId IN (values)</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels> fetchByWebshopid(Long... values) {
        return fetch(Webshopservicelevels.WEBSHOPSERVICELEVELS.WEBSHOPID, values);
    }

    /**
     * Fetch a unique record that has <code>webshopId = value</code>
     */
    public com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels fetchOneByWebshopid(Long value) {
        return fetchOne(Webshopservicelevels.WEBSHOPSERVICELEVELS.WEBSHOPID, value);
    }

    /**
     * Fetch a unique record that has <code>webshopId = value</code>
     */
    public Optional<com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels> fetchOptionalByWebshopid(Long value) {
        return fetchOptional(Webshopservicelevels.WEBSHOPSERVICELEVELS.WEBSHOPID, value);
    }

    /**
     * Fetch records that have <code>slcA BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels> fetchRangeOfSlca(Double lowerInclusive, Double upperInclusive) {
        return fetchRange(Webshopservicelevels.WEBSHOPSERVICELEVELS.SLCA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>slcA IN (values)</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels> fetchBySlca(Double... values) {
        return fetch(Webshopservicelevels.WEBSHOPSERVICELEVELS.SLCA, values);
    }

    /**
     * Fetch records that have <code>slcB BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels> fetchRangeOfSlcb(Double lowerInclusive, Double upperInclusive) {
        return fetchRange(Webshopservicelevels.WEBSHOPSERVICELEVELS.SLCB, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>slcB IN (values)</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels> fetchBySlcb(Double... values) {
        return fetch(Webshopservicelevels.WEBSHOPSERVICELEVELS.SLCB, values);
    }

    /**
     * Fetch records that have <code>slcC BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels> fetchRangeOfSlcc(Double lowerInclusive, Double upperInclusive) {
        return fetchRange(Webshopservicelevels.WEBSHOPSERVICELEVELS.SLCC, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>slcC IN (values)</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels> fetchBySlcc(Double... values) {
        return fetch(Webshopservicelevels.WEBSHOPSERVICELEVELS.SLCC, values);
    }
}
