/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models;


import com.optiply.infrastructure.data.models.tables.Webshop;
import com.optiply.infrastructure.data.models.tables.Webshopemails;
import com.optiply.infrastructure.data.models.tables.Webshopservicelevels;
import com.optiply.infrastructure.data.models.tables.Webshopsettings;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>webshop</code>.
     */
    public static final Webshop WEBSHOP = Webshop.WEBSHOP;

    /**
     * The table <code>webshopEmails</code>.
     */
    public static final Webshopemails WEBSHOPEMAILS = Webshopemails.WEBSHOPEMAILS;

    /**
     * The table <code>webshopServiceLevels</code>.
     */
    public static final Webshopservicelevels WEBSHOPSERVICELEVELS = Webshopservicelevels.WEBSHOPSERVICELEVELS;

    /**
     * The table <code>webshopSettings</code>.
     */
    public static final Webshopsettings WEBSHOPSETTINGS = Webshopsettings.WEBSHOPSETTINGS;
}
