/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models;


import com.optiply.infrastructure.data.models.tables.Webshop;
import com.optiply.infrastructure.data.models.tables.Webshopemails;
import com.optiply.infrastructure.data.models.tables.Webshopservicelevels;
import com.optiply.infrastructure.data.models.tables.Webshopsettings;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>webshop</code>.
     */
    public final Webshop WEBSHOP = Webshop.WEBSHOP;

    /**
     * The table <code>webshopEmails</code>.
     */
    public final Webshopemails WEBSHOPEMAILS = Webshopemails.WEBSHOPEMAILS;

    /**
     * The table <code>webshopServiceLevels</code>.
     */
    public final Webshopservicelevels WEBSHOPSERVICELEVELS = Webshopservicelevels.WEBSHOPSERVICELEVELS;

    /**
     * The table <code>webshopSettings</code>.
     */
    public final Webshopsettings WEBSHOPSETTINGS = Webshopsettings.WEBSHOPSETTINGS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Webshop.WEBSHOP,
            Webshopemails.WEBSHOPEMAILS,
            Webshopservicelevels.WEBSHOPSERVICELEVELS,
            Webshopsettings.WEBSHOPSETTINGS
        );
    }
}
