/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models.tables.records;


import com.optiply.infrastructure.data.models.tables.Webshopemails;
import com.optiply.infrastructure.data.models.tables.interfaces.IWebshopemails;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebshopemailsRecord extends UpdatableRecordImpl<WebshopemailsRecord> implements Record3<Long, Long, String>, IWebshopemails {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>webshopEmails.addressId</code>.
     */
    @Override
    public WebshopemailsRecord setAddressid(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>webshopEmails.addressId</code>.
     */
    @Override
    public Long getAddressid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>webshopEmails.webshopId</code>.
     */
    @Override
    public WebshopemailsRecord setWebshopid(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>webshopEmails.webshopId</code>.
     */
    @Override
    public Long getWebshopid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>webshopEmails.address</code>.
     */
    @Override
    public WebshopemailsRecord setAddress(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>webshopEmails.address</code>.
     */
    @Override
    public String getAddress() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Webshopemails.WEBSHOPEMAILS.ADDRESSID;
    }

    @Override
    public Field<Long> field2() {
        return Webshopemails.WEBSHOPEMAILS.WEBSHOPID;
    }

    @Override
    public Field<String> field3() {
        return Webshopemails.WEBSHOPEMAILS.ADDRESS;
    }

    @Override
    public Long component1() {
        return getAddressid();
    }

    @Override
    public Long component2() {
        return getWebshopid();
    }

    @Override
    public String component3() {
        return getAddress();
    }

    @Override
    public Long value1() {
        return getAddressid();
    }

    @Override
    public Long value2() {
        return getWebshopid();
    }

    @Override
    public String value3() {
        return getAddress();
    }

    @Override
    public WebshopemailsRecord value1(Long value) {
        setAddressid(value);
        return this;
    }

    @Override
    public WebshopemailsRecord value2(Long value) {
        setWebshopid(value);
        return this;
    }

    @Override
    public WebshopemailsRecord value3(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public WebshopemailsRecord values(Long value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IWebshopemails from) {
        setAddressid(from.getAddressid());
        setWebshopid(from.getWebshopid());
        setAddress(from.getAddress());
    }

    @Override
    public <E extends IWebshopemails> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WebshopemailsRecord
     */
    public WebshopemailsRecord() {
        super(Webshopemails.WEBSHOPEMAILS);
    }

    /**
     * Create a detached, initialised WebshopemailsRecord
     */
    public WebshopemailsRecord(Long addressid, Long webshopid, String address) {
        super(Webshopemails.WEBSHOPEMAILS);

        setAddressid(addressid);
        setWebshopid(webshopid);
        setAddress(address);
    }

    /**
     * Create a detached, initialised WebshopemailsRecord
     */
    public WebshopemailsRecord(com.optiply.infrastructure.data.models.tables.pojos.Webshopemails value) {
        super(Webshopemails.WEBSHOPEMAILS);

        if (value != null) {
            setAddressid(value.getAddressid());
            setWebshopid(value.getWebshopid());
            setAddress(value.getAddress());
        }
    }
}
