/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models.tables.records;


import com.optiply.infrastructure.data.models.tables.Webshopservicelevels;
import com.optiply.infrastructure.data.models.tables.interfaces.IWebshopservicelevels;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebshopservicelevelsRecord extends UpdatableRecordImpl<WebshopservicelevelsRecord> implements Record4<Long, Double, Double, Double>, IWebshopservicelevels {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>webshopServiceLevels.webshopId</code>.
     */
    @Override
    public WebshopservicelevelsRecord setWebshopid(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>webshopServiceLevels.webshopId</code>.
     */
    @Override
    public Long getWebshopid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>webshopServiceLevels.slcA</code>.
     */
    @Override
    public WebshopservicelevelsRecord setSlca(Double value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>webshopServiceLevels.slcA</code>.
     */
    @Override
    public Double getSlca() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>webshopServiceLevels.slcB</code>.
     */
    @Override
    public WebshopservicelevelsRecord setSlcb(Double value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>webshopServiceLevels.slcB</code>.
     */
    @Override
    public Double getSlcb() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>webshopServiceLevels.slcC</code>.
     */
    @Override
    public WebshopservicelevelsRecord setSlcc(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>webshopServiceLevels.slcC</code>.
     */
    @Override
    public Double getSlcc() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Double, Double, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Double, Double, Double> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Webshopservicelevels.WEBSHOPSERVICELEVELS.WEBSHOPID;
    }

    @Override
    public Field<Double> field2() {
        return Webshopservicelevels.WEBSHOPSERVICELEVELS.SLCA;
    }

    @Override
    public Field<Double> field3() {
        return Webshopservicelevels.WEBSHOPSERVICELEVELS.SLCB;
    }

    @Override
    public Field<Double> field4() {
        return Webshopservicelevels.WEBSHOPSERVICELEVELS.SLCC;
    }

    @Override
    public Long component1() {
        return getWebshopid();
    }

    @Override
    public Double component2() {
        return getSlca();
    }

    @Override
    public Double component3() {
        return getSlcb();
    }

    @Override
    public Double component4() {
        return getSlcc();
    }

    @Override
    public Long value1() {
        return getWebshopid();
    }

    @Override
    public Double value2() {
        return getSlca();
    }

    @Override
    public Double value3() {
        return getSlcb();
    }

    @Override
    public Double value4() {
        return getSlcc();
    }

    @Override
    public WebshopservicelevelsRecord value1(Long value) {
        setWebshopid(value);
        return this;
    }

    @Override
    public WebshopservicelevelsRecord value2(Double value) {
        setSlca(value);
        return this;
    }

    @Override
    public WebshopservicelevelsRecord value3(Double value) {
        setSlcb(value);
        return this;
    }

    @Override
    public WebshopservicelevelsRecord value4(Double value) {
        setSlcc(value);
        return this;
    }

    @Override
    public WebshopservicelevelsRecord values(Long value1, Double value2, Double value3, Double value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IWebshopservicelevels from) {
        setWebshopid(from.getWebshopid());
        setSlca(from.getSlca());
        setSlcb(from.getSlcb());
        setSlcc(from.getSlcc());
    }

    @Override
    public <E extends IWebshopservicelevels> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WebshopservicelevelsRecord
     */
    public WebshopservicelevelsRecord() {
        super(Webshopservicelevels.WEBSHOPSERVICELEVELS);
    }

    /**
     * Create a detached, initialised WebshopservicelevelsRecord
     */
    public WebshopservicelevelsRecord(Long webshopid, Double slca, Double slcb, Double slcc) {
        super(Webshopservicelevels.WEBSHOPSERVICELEVELS);

        setWebshopid(webshopid);
        setSlca(slca);
        setSlcb(slcb);
        setSlcc(slcc);
    }

    /**
     * Create a detached, initialised WebshopservicelevelsRecord
     */
    public WebshopservicelevelsRecord(com.optiply.infrastructure.data.models.tables.pojos.Webshopservicelevels value) {
        super(Webshopservicelevels.WEBSHOPSERVICELEVELS);

        if (value != null) {
            setWebshopid(value.getWebshopid());
            setSlca(value.getSlca());
            setSlcb(value.getSlcb());
            setSlcc(value.getSlcc());
        }
    }
}
