/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models.tables.pojos;


import com.optiply.infrastructure.data.models.tables.interfaces.IWebshopemails;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Webshopemails implements IWebshopemails {

    private static final long serialVersionUID = 1L;

    private Long   addressid;
    private Long   webshopid;
    private String address;

    public Webshopemails() {}

    public Webshopemails(IWebshopemails value) {
        this.addressid = value.getAddressid();
        this.webshopid = value.getWebshopid();
        this.address = value.getAddress();
    }

    public Webshopemails(
        Long   addressid,
        Long   webshopid,
        String address
    ) {
        this.addressid = addressid;
        this.webshopid = webshopid;
        this.address = address;
    }

    /**
     * Getter for <code>webshopEmails.addressId</code>.
     */
    @Override
    public Long getAddressid() {
        return this.addressid;
    }

    /**
     * Setter for <code>webshopEmails.addressId</code>.
     */
    @Override
    public Webshopemails setAddressid(Long addressid) {
        this.addressid = addressid;
        return this;
    }

    /**
     * Getter for <code>webshopEmails.webshopId</code>.
     */
    @Override
    public Long getWebshopid() {
        return this.webshopid;
    }

    /**
     * Setter for <code>webshopEmails.webshopId</code>.
     */
    @Override
    public Webshopemails setWebshopid(Long webshopid) {
        this.webshopid = webshopid;
        return this;
    }

    /**
     * Getter for <code>webshopEmails.address</code>.
     */
    @Override
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>webshopEmails.address</code>.
     */
    @Override
    public Webshopemails setAddress(String address) {
        this.address = address;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Webshopemails other = (Webshopemails) obj;
        if (addressid == null) {
            if (other.addressid != null)
                return false;
        }
        else if (!addressid.equals(other.addressid))
            return false;
        if (webshopid == null) {
            if (other.webshopid != null)
                return false;
        }
        else if (!webshopid.equals(other.webshopid))
            return false;
        if (address == null) {
            if (other.address != null)
                return false;
        }
        else if (!address.equals(other.address))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.addressid == null) ? 0 : this.addressid.hashCode());
        result = prime * result + ((this.webshopid == null) ? 0 : this.webshopid.hashCode());
        result = prime * result + ((this.address == null) ? 0 : this.address.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Webshopemails (");

        sb.append(addressid);
        sb.append(", ").append(webshopid);
        sb.append(", ").append(address);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IWebshopemails from) {
        setAddressid(from.getAddressid());
        setWebshopid(from.getWebshopid());
        setAddress(from.getAddress());
    }

    @Override
    public <E extends IWebshopemails> E into(E into) {
        into.from(this);
        return into;
    }
}
