/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models.tables.pojos;


import com.optiply.infrastructure.data.models.tables.interfaces.IWebshop;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Webshop implements IWebshop {

    private static final long serialVersionUID = 1L;

    private Long   webshopid;
    private String handle;
    private String url;
    private Short  interestrate;

    public Webshop() {}

    public Webshop(IWebshop value) {
        this.webshopid = value.getWebshopid();
        this.handle = value.getHandle();
        this.url = value.getUrl();
        this.interestrate = value.getInterestrate();
    }

    public Webshop(
        Long   webshopid,
        String handle,
        String url,
        Short  interestrate
    ) {
        this.webshopid = webshopid;
        this.handle = handle;
        this.url = url;
        this.interestrate = interestrate;
    }

    /**
     * Getter for <code>webshop.webshopId</code>.
     */
    @Override
    public Long getWebshopid() {
        return this.webshopid;
    }

    /**
     * Setter for <code>webshop.webshopId</code>.
     */
    @Override
    public Webshop setWebshopid(Long webshopid) {
        this.webshopid = webshopid;
        return this;
    }

    /**
     * Getter for <code>webshop.handle</code>.
     */
    @Override
    public String getHandle() {
        return this.handle;
    }

    /**
     * Setter for <code>webshop.handle</code>.
     */
    @Override
    public Webshop setHandle(String handle) {
        this.handle = handle;
        return this;
    }

    /**
     * Getter for <code>webshop.url</code>.
     */
    @Override
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>webshop.url</code>.
     */
    @Override
    public Webshop setUrl(String url) {
        this.url = url;
        return this;
    }

    /**
     * Getter for <code>webshop.interestRate</code>.
     */
    @Override
    public Short getInterestrate() {
        return this.interestrate;
    }

    /**
     * Setter for <code>webshop.interestRate</code>.
     */
    @Override
    public Webshop setInterestrate(Short interestrate) {
        this.interestrate = interestrate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Webshop other = (Webshop) obj;
        if (webshopid == null) {
            if (other.webshopid != null)
                return false;
        }
        else if (!webshopid.equals(other.webshopid))
            return false;
        if (handle == null) {
            if (other.handle != null)
                return false;
        }
        else if (!handle.equals(other.handle))
            return false;
        if (url == null) {
            if (other.url != null)
                return false;
        }
        else if (!url.equals(other.url))
            return false;
        if (interestrate == null) {
            if (other.interestrate != null)
                return false;
        }
        else if (!interestrate.equals(other.interestrate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.webshopid == null) ? 0 : this.webshopid.hashCode());
        result = prime * result + ((this.handle == null) ? 0 : this.handle.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.interestrate == null) ? 0 : this.interestrate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Webshop (");

        sb.append(webshopid);
        sb.append(", ").append(handle);
        sb.append(", ").append(url);
        sb.append(", ").append(interestrate);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IWebshop from) {
        setWebshopid(from.getWebshopid());
        setHandle(from.getHandle());
        setUrl(from.getUrl());
        setInterestrate(from.getInterestrate());
    }

    @Override
    public <E extends IWebshop> E into(E into) {
        into.from(this);
        return into;
    }
}
