/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IWebshop extends Serializable {

    /**
     * Setter for <code>webshop.webshopId</code>.
     */
    public IWebshop setWebshopid(Long value);

    /**
     * Getter for <code>webshop.webshopId</code>.
     */
    public Long getWebshopid();

    /**
     * Setter for <code>webshop.handle</code>.
     */
    public IWebshop setHandle(String value);

    /**
     * Getter for <code>webshop.handle</code>.
     */
    public String getHandle();

    /**
     * Setter for <code>webshop.url</code>.
     */
    public IWebshop setUrl(String value);

    /**
     * Getter for <code>webshop.url</code>.
     */
    public String getUrl();

    /**
     * Setter for <code>webshop.interestRate</code>.
     */
    public IWebshop setInterestrate(Short value);

    /**
     * Getter for <code>webshop.interestRate</code>.
     */
    public Short getInterestrate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IWebshop
     */
    public void from(IWebshop from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IWebshop
     */
    public <E extends IWebshop> E into(E into);
}
