/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models.tables.daos;


import com.optiply.infrastructure.data.models.tables.Webshop;
import com.optiply.infrastructure.data.models.tables.records.WebshopRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebshopDao extends DAOImpl<WebshopRecord, com.optiply.infrastructure.data.models.tables.pojos.Webshop, Long> {

    /**
     * Create a new WebshopDao without any configuration
     */
    public WebshopDao() {
        super(Webshop.WEBSHOP, com.optiply.infrastructure.data.models.tables.pojos.Webshop.class);
    }

    /**
     * Create a new WebshopDao with an attached configuration
     */
    public WebshopDao(Configuration configuration) {
        super(Webshop.WEBSHOP, com.optiply.infrastructure.data.models.tables.pojos.Webshop.class, configuration);
    }

    @Override
    public Long getId(com.optiply.infrastructure.data.models.tables.pojos.Webshop object) {
        return object.getWebshopid();
    }

    /**
     * Fetch records that have <code>webshopId BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshop> fetchRangeOfWebshopid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Webshop.WEBSHOP.WEBSHOPID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>webshopId IN (values)</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshop> fetchByWebshopid(Long... values) {
        return fetch(Webshop.WEBSHOP.WEBSHOPID, values);
    }

    /**
     * Fetch a unique record that has <code>webshopId = value</code>
     */
    public com.optiply.infrastructure.data.models.tables.pojos.Webshop fetchOneByWebshopid(Long value) {
        return fetchOne(Webshop.WEBSHOP.WEBSHOPID, value);
    }

    /**
     * Fetch a unique record that has <code>webshopId = value</code>
     */
    public Optional<com.optiply.infrastructure.data.models.tables.pojos.Webshop> fetchOptionalByWebshopid(Long value) {
        return fetchOptional(Webshop.WEBSHOP.WEBSHOPID, value);
    }

    /**
     * Fetch records that have <code>handle BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshop> fetchRangeOfHandle(String lowerInclusive, String upperInclusive) {
        return fetchRange(Webshop.WEBSHOP.HANDLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>handle IN (values)</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshop> fetchByHandle(String... values) {
        return fetch(Webshop.WEBSHOP.HANDLE, values);
    }

    /**
     * Fetch a unique record that has <code>handle = value</code>
     */
    public com.optiply.infrastructure.data.models.tables.pojos.Webshop fetchOneByHandle(String value) {
        return fetchOne(Webshop.WEBSHOP.HANDLE, value);
    }

    /**
     * Fetch a unique record that has <code>handle = value</code>
     */
    public Optional<com.optiply.infrastructure.data.models.tables.pojos.Webshop> fetchOptionalByHandle(String value) {
        return fetchOptional(Webshop.WEBSHOP.HANDLE, value);
    }

    /**
     * Fetch records that have <code>url BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshop> fetchRangeOfUrl(String lowerInclusive, String upperInclusive) {
        return fetchRange(Webshop.WEBSHOP.URL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshop> fetchByUrl(String... values) {
        return fetch(Webshop.WEBSHOP.URL, values);
    }

    /**
     * Fetch a unique record that has <code>url = value</code>
     */
    public com.optiply.infrastructure.data.models.tables.pojos.Webshop fetchOneByUrl(String value) {
        return fetchOne(Webshop.WEBSHOP.URL, value);
    }

    /**
     * Fetch a unique record that has <code>url = value</code>
     */
    public Optional<com.optiply.infrastructure.data.models.tables.pojos.Webshop> fetchOptionalByUrl(String value) {
        return fetchOptional(Webshop.WEBSHOP.URL, value);
    }

    /**
     * Fetch records that have <code>interestRate BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshop> fetchRangeOfInterestrate(Short lowerInclusive, Short upperInclusive) {
        return fetchRange(Webshop.WEBSHOP.INTERESTRATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>interestRate IN (values)</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshop> fetchByInterestrate(Short... values) {
        return fetch(Webshop.WEBSHOP.INTERESTRATE, values);
    }
}
