/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models.tables.daos;


import com.optiply.infrastructure.data.models.tables.Webshopsettings;
import com.optiply.infrastructure.data.models.tables.records.WebshopsettingsRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebshopsettingsDao extends DAOImpl<WebshopsettingsRecord, com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings, Long> {

    /**
     * Create a new WebshopsettingsDao without any configuration
     */
    public WebshopsettingsDao() {
        super(Webshopsettings.WEBSHOPSETTINGS, com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings.class);
    }

    /**
     * Create a new WebshopsettingsDao with an attached configuration
     */
    public WebshopsettingsDao(Configuration configuration) {
        super(Webshopsettings.WEBSHOPSETTINGS, com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings.class, configuration);
    }

    @Override
    public Long getId(com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings object) {
        return object.getWebshopid();
    }

    /**
     * Fetch records that have <code>webshopId BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings> fetchRangeOfWebshopid(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Webshopsettings.WEBSHOPSETTINGS.WEBSHOPID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>webshopId IN (values)</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings> fetchByWebshopid(Long... values) {
        return fetch(Webshopsettings.WEBSHOPSETTINGS.WEBSHOPID, values);
    }

    /**
     * Fetch a unique record that has <code>webshopId = value</code>
     */
    public com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings fetchOneByWebshopid(Long value) {
        return fetchOne(Webshopsettings.WEBSHOPSETTINGS.WEBSHOPID, value);
    }

    /**
     * Fetch a unique record that has <code>webshopId = value</code>
     */
    public Optional<com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings> fetchOptionalByWebshopid(Long value) {
        return fetchOptional(Webshopsettings.WEBSHOPSETTINGS.WEBSHOPID, value);
    }

    /**
     * Fetch records that have <code>currency BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings> fetchRangeOfCurrency(String lowerInclusive, String upperInclusive) {
        return fetchRange(Webshopsettings.WEBSHOPSETTINGS.CURRENCY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>currency IN (values)</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings> fetchByCurrency(String... values) {
        return fetch(Webshopsettings.WEBSHOPSETTINGS.CURRENCY, values);
    }

    /**
     * Fetch records that have <code>runJobs BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings> fetchRangeOfRunjobs(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Webshopsettings.WEBSHOPSETTINGS.RUNJOBS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>runJobs IN (values)</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings> fetchByRunjobs(Boolean... values) {
        return fetch(Webshopsettings.WEBSHOPSETTINGS.RUNJOBS, values);
    }

    /**
     * Fetch records that have <code>multiSupply BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings> fetchRangeOfMultisupply(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(Webshopsettings.WEBSHOPSETTINGS.MULTISUPPLY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>multiSupply IN (values)</code>
     */
    public List<com.optiply.infrastructure.data.models.tables.pojos.Webshopsettings> fetchByMultisupply(Boolean... values) {
        return fetch(Webshopsettings.WEBSHOPSETTINGS.MULTISUPPLY, values);
    }
}
