/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models.tables;


import com.optiply.infrastructure.data.models.DefaultSchema;
import com.optiply.infrastructure.data.models.Keys;
import com.optiply.infrastructure.data.models.tables.records.WebshopsettingsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Webshopsettings extends TableImpl<WebshopsettingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>webshopSettings</code>
     */
    public static final Webshopsettings WEBSHOPSETTINGS = new Webshopsettings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WebshopsettingsRecord> getRecordType() {
        return WebshopsettingsRecord.class;
    }

    /**
     * The column <code>webshopSettings.webshopId</code>.
     */
    public final TableField<WebshopsettingsRecord, Long> WEBSHOPID = createField(DSL.name("webshopId"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>webshopSettings.currency</code>.
     */
    public final TableField<WebshopsettingsRecord, String> CURRENCY = createField(DSL.name("currency"), SQLDataType.VARCHAR(3).nullable(false).defaultValue(DSL.field("'EUR'", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>webshopSettings.runJobs</code>.
     */
    public final TableField<WebshopsettingsRecord, Boolean> RUNJOBS = createField(DSL.name("runJobs"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("'true'", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>webshopSettings.multiSupply</code>.
     */
    public final TableField<WebshopsettingsRecord, Boolean> MULTISUPPLY = createField(DSL.name("multiSupply"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("'false'", SQLDataType.BOOLEAN)), this, "");

    private Webshopsettings(Name alias, Table<WebshopsettingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Webshopsettings(Name alias, Table<WebshopsettingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>webshopSettings</code> table reference
     */
    public Webshopsettings(String alias) {
        this(DSL.name(alias), WEBSHOPSETTINGS);
    }

    /**
     * Create an aliased <code>webshopSettings</code> table reference
     */
    public Webshopsettings(Name alias) {
        this(alias, WEBSHOPSETTINGS);
    }

    /**
     * Create a <code>webshopSettings</code> table reference
     */
    public Webshopsettings() {
        this(DSL.name("webshopSettings"), null);
    }

    public <O extends Record> Webshopsettings(Table<O> child, ForeignKey<O, WebshopsettingsRecord> key) {
        super(child, key, WEBSHOPSETTINGS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<WebshopsettingsRecord> getPrimaryKey() {
        return Keys.WEBSHOPSETTINGS_PK;
    }

    @Override
    public List<ForeignKey<WebshopsettingsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WEBSHOPSETTINGS_FK0);
    }

    private transient Webshop _webshop;

    /**
     * Get the implicit join path to the <code>PUBLIC.webshop</code> table.
     */
    public Webshop webshop() {
        if (_webshop == null)
            _webshop = new Webshop(this, Keys.WEBSHOPSETTINGS_FK0);

        return _webshop;
    }

    @Override
    public Webshopsettings as(String alias) {
        return new Webshopsettings(DSL.name(alias), this);
    }

    @Override
    public Webshopsettings as(Name alias) {
        return new Webshopsettings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Webshopsettings rename(String name) {
        return new Webshopsettings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Webshopsettings rename(Name name) {
        return new Webshopsettings(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, Boolean, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
