/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IWebshopservicelevels extends Serializable {

    /**
     * Setter for <code>webshopServiceLevels.webshopId</code>.
     */
    public IWebshopservicelevels setWebshopid(Long value);

    /**
     * Getter for <code>webshopServiceLevels.webshopId</code>.
     */
    public Long getWebshopid();

    /**
     * Setter for <code>webshopServiceLevels.slcA</code>.
     */
    public IWebshopservicelevels setSlca(Double value);

    /**
     * Getter for <code>webshopServiceLevels.slcA</code>.
     */
    public Double getSlca();

    /**
     * Setter for <code>webshopServiceLevels.slcB</code>.
     */
    public IWebshopservicelevels setSlcb(Double value);

    /**
     * Getter for <code>webshopServiceLevels.slcB</code>.
     */
    public Double getSlcb();

    /**
     * Setter for <code>webshopServiceLevels.slcC</code>.
     */
    public IWebshopservicelevels setSlcc(Double value);

    /**
     * Getter for <code>webshopServiceLevels.slcC</code>.
     */
    public Double getSlcc();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IWebshopservicelevels
     */
    public void from(IWebshopservicelevels from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IWebshopservicelevels
     */
    public <E extends IWebshopservicelevels> E into(E into);
}
