/*
 * This file is generated by jOOQ.
 */
package com.optiply.infrastructure.data.models.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IWebshopsettings extends Serializable {

    /**
     * Setter for <code>webshopSettings.webshopId</code>.
     */
    public IWebshopsettings setWebshopid(Long value);

    /**
     * Getter for <code>webshopSettings.webshopId</code>.
     */
    public Long getWebshopid();

    /**
     * Setter for <code>webshopSettings.currency</code>.
     */
    public IWebshopsettings setCurrency(String value);

    /**
     * Getter for <code>webshopSettings.currency</code>.
     */
    public String getCurrency();

    /**
     * Setter for <code>webshopSettings.runJobs</code>.
     */
    public IWebshopsettings setRunjobs(Boolean value);

    /**
     * Getter for <code>webshopSettings.runJobs</code>.
     */
    public Boolean getRunjobs();

    /**
     * Setter for <code>webshopSettings.multiSupply</code>.
     */
    public IWebshopsettings setMultisupply(Boolean value);

    /**
     * Getter for <code>webshopSettings.multiSupply</code>.
     */
    public Boolean getMultisupply();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IWebshopsettings
     */
    public void from(IWebshopsettings from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IWebshopsettings
     */
    public <E extends IWebshopsettings> E into(E into);
}
